---
title: "teoria previa a actividad analisis funcional"
author: "miguel angel vicente mesonero"
date: "2026-01-27"
output: html_document
---
Objetivo: Aprender a realizar el análisis funcional

1. Instalación de paquete AnnotationDbi para anotación biológica, incluye métodos para acceder y realizar búsquedas en bases de datos basadas en SQL.

```
if(!requireNamespace("BiocManager",quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("AnnotationDbi")
```

2. Instalo le paquete para Genome wide annotation for Human
```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("org.Hs.eg.db", force = TRUE)
```

3. Llamo a los paquetes

```
library(AnnotationDbi)
library(org.Hs.eg.db)
```

4. Exploración de la base de datos

```
columns(org.Hs.eg.db) #información a la que puedo acceder

help("ENTREZID") # Explicación de la información de la línea anterior

org.Hs.eg.db # Muestra información de la base de datos

```

5. Generamos una lista aleatorio de 100 genes

```
#Para poder reproducir el análisis, siempre creará los mismos genes, aunque el código diga que lo haga aleatorio

set.seed(99) 

# Ahora el código para generar la lista. keys() sirve para seleccionar dentro de la db

entrezID <- keys(org.Hs.eg.db, keytype = "ENTREZID")[sample(1:61000,100,replace = FALSE)]

#Exploro el objeto creado

head(entrezID,10)
 
```

6. Anotación de los 100 genes con el método select()
El siguiente código selecciona dentro de la base de datos, según la clave del objeto que incluye la lista de ids que cremos antes, y coge la informacion de las columnas que vamos a poner con columns = ; dice que la keytype se creara en una columna ENTREZID que usará la información de key.

Podemos ver esta información en ?select

*Arguments*

**x**	
the AnnotationDb object. But in practice this will mean an object derived from an AnnotationDb object such as a OrgDb or ChipDb object.

**keys**	
the keys to select records for from the database. All possible keys are returned by using the keys method.

**columns**	
the columns or kinds of things that can be retrieved from the database. As with keys, all possible columns are returned by using the columns method.

**keytype**	
the keytype that matches the keys used. For the select methods, this is used to indicate the kind of ID being used with the keys argument. For the keys method this is used to indicate which kind of keys are desired from keys

```
annot <- select (org.Hs.eg.db, keys = entrezID, columns = c("SYMBOL","GENENAME","GO","UNIPROT","OMIM"),keytype = "ENTREZID")
```

